"""AIVARA Model Integrity Subsystem (Phase 7).

Provides safe ingestion, format detection, resource bounding, static parsing,
deterministic metadata normalization, and hierarchical cryptographic fingerprinting
for untrusted AI/CV model artifacts.
"""

from aivara.model_integrity.exceptions import (
    ModelCorruptionError,
    ModelIntegrityError,
    ParsingError,
    ProhibitedFormatError,
    ResourceLimitExceededError,
    UntrustedArtifactSecurityError,
)
from aivara.model_integrity.fingerprinting import (
    EMPTY_WEIGHT_ROOT_HEX,
    ContractRepresentation,
    DuplicateTensorLeafError,
    FingerprintingError,
    HierarchicalFingerprintResult,
    InvalidMerkleProofError,
    MasterFingerprintBinding,
    MerkleInclusionProof,
    MerkleProofStep,
    ModelFingerprintingService,
    ProofStepDirection,
    StructuralRepresentation,
    TensorLeafDescriptor,
    WeightContentUnavailableError,
    WeightMerkleResult,
    WeightMerkleTree,
    build_contract_representation,
    build_structural_representation,
    compute_artifact_hash,
    compute_contract_hash,
    compute_internal_node_hash,
    compute_master_fingerprint,
    compute_structural_hash,
    compute_tensor_leaf_hash,
    compute_weight_merkle_root,
    extract_tensor_leaves,
    generate_weight_inclusion_proof,
    verify_weight_inclusion_proof,
)
from aivara.model_integrity.contract_verification import (
    ContractCompleteness,
    ContractFinding,
    ContractFindingCode,
    ContractStatus,
    ContractVerificationResult,
    ModelContractVerificationService,
    PreprocessingDeclaration,
    PreprocessingSource,
    ValidatedInputContract,
    ValidatedOutputContract,
    inspect_input_contract,
    inspect_output_contract,
    validate_contract_integrity,
    validate_preprocessing_consistency,
)
from aivara.model_integrity.comparison import (
    ArtifactComparisonStatus,
    ComparisonStatus,
    ContractComparisonStatus,
    ContractDifferenceRecord,
    DriftClassification,
    ModelComparisonResult,
    ModelComparisonService,
    StructuralComparisonStatus,
    StructuralDifferenceRecord,
    TensorChangeRecord,
    TensorChangeType,
    WeightComparisonStatus,
    attribute_tensor_changes,
    classify_drift,
    compare_artifact_hashes,
    compare_contract_hashes,
    compare_master_fingerprints,
    compare_structural_hashes,
    compare_weight_roots,
    determine_comparison_status,
    diff_contract_metadata,
    diff_structural_metadata,
)
from aivara.model_integrity.evidence import (
    ModelEvidenceType,
    ModelIntegrityAssessmentPayload,
    ModelIntegrityEvidenceService,
    build_artifact_identity_evidence,
    build_comparison_evidence,
    build_contract_evidence,
    build_master_fingerprint_evidence,
    build_structural_fingerprint_evidence,
    build_tensor_attribution_evidence,
    build_weight_merkle_evidence,
    map_model_integrity_to_findings,
)
from aivara.model_integrity.format_detection import (
    POLICY_MAP,
    detect_model_format,
)
from aivara.model_integrity.limits import (
    DEFAULT_LIMITS,
    ModelIngestionLimits,
)
from aivara.model_integrity.normalization import (
    build_normalized_metadata,
    canonicalize_normalized_metadata,
)
from aivara.model_integrity.parsers import (
    BaseModelParser,
    ONNXParser,
    ParsedModelData,
    PyTorchStateDictParser,
    SafetensorsParser,
    TorchScriptParser,
)
from aivara.model_integrity.schemas import (
    FormatDetectionResult,
    InputContractDescriptor,
    InspectionPolicy,
    InspectionStatus,
    ModelFormat,
    ModelInspectionResult,
    NormalizedModelMetadata,
    OperatorDescriptor,
    OutputContractDescriptor,
    ReasonCode,
    TensorDescriptor,
)
from aivara.model_integrity.security import (
    compute_streaming_sha256,
    normalize_and_sanitize_path,
    validate_artifact_file,
)
from aivara.model_integrity.service import ModelIngestionService

__all__ = [
    # Core Services
    "ModelIngestionService",
    "ModelFingerprintingService",
    "ModelContractVerificationService",
    "ModelComparisonService",
    "ModelIntegrityEvidenceService",
    # Schemas & Enums
    "ModelFormat",
    "InspectionPolicy",
    "InspectionStatus",
    "ReasonCode",
    "ContractStatus",
    "ContractCompleteness",
    "PreprocessingSource",
    "ContractFindingCode",
    "ContractFinding",
    "ValidatedInputContract",
    "ValidatedOutputContract",
    "PreprocessingDeclaration",
    "ContractVerificationResult",
    "ComparisonStatus",
    "ArtifactComparisonStatus",
    "StructuralComparisonStatus",
    "WeightComparisonStatus",
    "ContractComparisonStatus",
    "DriftClassification",
    "TensorChangeType",
    "TensorChangeRecord",
    "StructuralDifferenceRecord",
    "ContractDifferenceRecord",
    "ModelComparisonResult",
    "ModelEvidenceType",
    "ModelIntegrityAssessmentPayload",
    "TensorDescriptor",
    "InputContractDescriptor",
    "OutputContractDescriptor",
    "OperatorDescriptor",
    "FormatDetectionResult",
    "NormalizedModelMetadata",
    "ModelInspectionResult",
    "StructuralRepresentation",
    "ContractRepresentation",
    "TensorLeafDescriptor",
    "WeightMerkleResult",
    "MasterFingerprintBinding",
    "HierarchicalFingerprintResult",
    "MerkleInclusionProof",
    "MerkleProofStep",
    "ProofStepDirection",
    # Limits
    "ModelIngestionLimits",
    "DEFAULT_LIMITS",
    # Exceptions
    "ModelIntegrityError",
    "UntrustedArtifactSecurityError",
    "ProhibitedFormatError",
    "ModelCorruptionError",
    "ResourceLimitExceededError",
    "ParsingError",
    "FingerprintingError",
    "WeightContentUnavailableError",
    "InvalidMerkleProofError",
    "DuplicateTensorLeafError",
    # Parsers
    "BaseModelParser",
    "ParsedModelData",
    "SafetensorsParser",
    "ONNXParser",
    "PyTorchStateDictParser",
    "TorchScriptParser",
    # Cryptographic & Fingerprinting Functions
    "detect_model_format",
    "build_normalized_metadata",
    "canonicalize_normalized_metadata",
    "validate_artifact_file",
    "normalize_and_sanitize_path",
    "compute_streaming_sha256",
    "compute_artifact_hash",
    "build_structural_representation",
    "compute_structural_hash",
    "build_contract_representation",
    "compute_contract_hash",
    "extract_tensor_leaves",
    "compute_tensor_leaf_hash",
    "compute_weight_merkle_root",
    "compute_internal_node_hash",
    "generate_weight_inclusion_proof",
    "verify_weight_inclusion_proof",
    "compute_master_fingerprint",
    "WeightMerkleTree",
    "EMPTY_WEIGHT_ROOT_HEX",
    "POLICY_MAP",
]
