"""Authoritative enums for AIVARA Phase 10 Inference Integrity."""

from __future__ import annotations

from enum import Enum


class InferenceIntegrityStatus(str, Enum):
    """Authoritative integrity verification status taxonomy."""

    VERIFIED = "VERIFIED"
    INVALID = "INVALID"
    MISSING = "MISSING"
    UNAVAILABLE = "UNAVAILABLE"
    MISMATCHED = "MISMATCHED"
    UNVERIFIABLE = "UNVERIFIABLE"


class InputKind(str, Enum):
    """Supported inference input categories."""

    TENSOR = "TENSOR"
    BATCHED_TENSOR = "BATCHED_TENSOR"
    IMAGE_FILE = "IMAGE_FILE"
    STRUCTURED = "STRUCTURED"


class InputLayout(str, Enum):
    """Declared or inferred tensor dimension layout."""

    GRAYSCALE_2D = "GRAYSCALE_2D"       # (H, W)
    HWC = "HWC"                         # (H, W, C)
    CHW = "CHW"                         # (C, H, W)
    NHWC = "NHWC"                       # (N, H, W, C)
    NCHW = "NCHW"                       # (N, C, H, W)
    VECTOR_1D = "VECTOR_1D"             # (D,)
    BATCH_VECTOR_2D = "BATCH_VECTOR_2D" # (N, D)
    TENSOR_ND = "TENSOR_ND"             # General N-D tensor
    STRUCTURED = "STRUCTURED"           # Key-value or list structure
    UNKNOWN = "UNKNOWN"                 # Ambiguous or unidentified layout


class ValueRangeKind(str, Enum):
    """Categorical value range classification for input data."""

    UNIT_FLOAT = "UNIT_FLOAT"           # [0.0, 1.0]
    ZERO_CENTERED = "ZERO_CENTERED"     # [-1.0, 1.0]
    BYTE_INTEGER = "BYTE_INTEGER"       # [0, 255]
    UNBOUNDED_FLOAT = "UNBOUNDED_FLOAT" # General finite floats
    UNKNOWN = "UNKNOWN"                 # Non-numeric or unidentified


class InferenceFindingCode(str, Enum):
    """Technical, observational finding codes for inference validation."""

    # Input Boundary Findings (Phase 10.2)
    INPUT_NONFINITE_VALUE = "INPUT_NONFINITE_VALUE"
    INPUT_UNSUPPORTED_DTYPE = "INPUT_UNSUPPORTED_DTYPE"
    INPUT_SHAPE_INVALID = "INPUT_SHAPE_INVALID"
    INPUT_RESOURCE_LIMIT_EXCEEDED = "INPUT_RESOURCE_LIMIT_EXCEEDED"
    INPUT_PATH_TRAVERSAL_DETECTED = "INPUT_PATH_TRAVERSAL_DETECTED"
    INPUT_FILE_NOT_FOUND = "INPUT_FILE_NOT_FOUND"
    INPUT_FILE_UNREADABLE = "INPUT_FILE_UNREADABLE"
    INPUT_IMAGE_MALFORMED = "INPUT_IMAGE_MALFORMED"
    INPUT_IMAGE_UNSUPPORTED_FORMAT = "INPUT_IMAGE_UNSUPPORTED_FORMAT"
    INPUT_RANGE_MISMATCH = "INPUT_RANGE_MISMATCH"
    INPUT_LAYOUT_AMBIGUOUS = "INPUT_LAYOUT_AMBIGUOUS"
    INPUT_MUTATION_DETECTED = "INPUT_MUTATION_DETECTED"
    INPUT_STRUCTURED_INVALID = "INPUT_STRUCTURED_INVALID"
    INPUT_SPECIAL_FILE_REJECTED = "INPUT_SPECIAL_FILE_REJECTED"

    # Input-Model Binding Findings (Phase 10.3)
    BINDING_PROJECT_MISMATCH = "BINDING_PROJECT_MISMATCH"
    BINDING_INPUT_NOT_VERIFIED = "BINDING_INPUT_NOT_VERIFIED"
    BINDING_MODEL_NOT_VERIFIED = "BINDING_MODEL_NOT_VERIFIED"
    BINDING_HASH_MISMATCH = "BINDING_HASH_MISMATCH"
    BINDING_MALFORMED_HASH = "BINDING_MALFORMED_HASH"
    BINDING_INCONSISTENT_IDENTITY = "BINDING_INCONSISTENT_IDENTITY"
    BINDING_UNSUPPORTED_SCHEMA = "BINDING_UNSUPPORTED_SCHEMA"

    # Preprocessing & Contract Findings (Phase 10.4)
    PREPROCESSING_CONTRACT_INVALID = "PREPROCESSING_CONTRACT_INVALID"
    PREPROCESSING_PARAMETER_NONFINITE = "PREPROCESSING_PARAMETER_NONFINITE"
    PREPROCESSING_DIMENSION_INVALID = "PREPROCESSING_DIMENSION_INVALID"
    PREPROCESSING_CROP_OUT_OF_BOUNDS = "PREPROCESSING_CROP_OUT_OF_BOUNDS"
    PREPROCESSING_PAD_INVALID = "PREPROCESSING_PAD_INVALID"
    PREPROCESSING_NORMALIZATION_INVALID = "PREPROCESSING_NORMALIZATION_INVALID"
    PREPROCESSING_UNSUPPORTED_OPERATION = "PREPROCESSING_UNSUPPORTED_OPERATION"
    PREPROCESSING_LAYOUT_MISMATCH = "PREPROCESSING_LAYOUT_MISMATCH"
    PREPROCESSING_CHANNEL_MISMATCH = "PREPROCESSING_CHANNEL_MISMATCH"
    PREPROCESSING_DTYPE_MISMATCH = "PREPROCESSING_DTYPE_MISMATCH"
    PREPROCESSING_RESOURCE_EXCEEDED = "PREPROCESSING_RESOURCE_EXCEEDED"
    PREPROCESSING_HASH_MISMATCH = "PREPROCESSING_HASH_MISMATCH"
    PREPROCESSING_MODEL_CONTRACT_UNAVAILABLE = "PREPROCESSING_MODEL_CONTRACT_UNAVAILABLE"
    PREPROCESSING_MODEL_CONTRACT_UNVERIFIABLE = "PREPROCESSING_MODEL_CONTRACT_UNVERIFIABLE"
    PREPROCESSING_TRANSFORM_FAILED = "PREPROCESSING_TRANSFORM_FAILED"

    # Execution Integrity Findings (Phase 10.5)
    EXECUTION_POLICY_VIOLATION = "EXECUTION_POLICY_VIOLATION"
    EXECUTION_PROVIDER_UNAVAILABLE = "EXECUTION_PROVIDER_UNAVAILABLE"
    EXECUTION_TIMEOUT = "EXECUTION_TIMEOUT"
    EXECUTION_CANCELLED = "EXECUTION_CANCELLED"
    EXECUTION_RESOURCE_EXCEEDED = "EXECUTION_RESOURCE_EXCEEDED"
    EXECUTION_MODEL_UNAVAILABLE = "EXECUTION_MODEL_UNAVAILABLE"
    EXECUTION_MODEL_UNVERIFIABLE = "EXECUTION_MODEL_UNVERIFIABLE"
    EXECUTION_MODEL_INVALID = "EXECUTION_MODEL_INVALID"
    EXECUTION_INPUT_MISMATCH = "EXECUTION_INPUT_MISMATCH"
    EXECUTION_PREPROCESSING_MISMATCH = "EXECUTION_PREPROCESSING_MISMATCH"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"
    EXECUTION_NONFINITE_OUTPUT = "EXECUTION_NONFINITE_OUTPUT"
    EXECUTION_HASH_MISMATCH = "EXECUTION_HASH_MISMATCH"

    # Output Schema & Numerical Integrity Findings (Phase 10.6)
    OUTPUT_SCHEMA_INVALID = "OUTPUT_SCHEMA_INVALID"
    OUTPUT_COUNT_MISMATCH = "OUTPUT_COUNT_MISMATCH"
    OUTPUT_ORDER_MISMATCH = "OUTPUT_ORDER_MISMATCH"
    OUTPUT_NAME_MISSING = "OUTPUT_NAME_MISSING"
    OUTPUT_NAME_MISMATCH = "OUTPUT_NAME_MISMATCH"
    OUTPUT_DTYPE_MISMATCH = "OUTPUT_DTYPE_MISMATCH"
    OUTPUT_RANK_MISMATCH = "OUTPUT_RANK_MISMATCH"
    OUTPUT_SHAPE_MISMATCH = "OUTPUT_SHAPE_MISMATCH"
    OUTPUT_DIMENSION_INVALID = "OUTPUT_DIMENSION_INVALID"
    OUTPUT_NONFINITE = "OUTPUT_NONFINITE"
    OUTPUT_NAN = "OUTPUT_NAN"
    OUTPUT_INFINITY = "OUTPUT_INFINITY"
    OUTPUT_DOMAIN_INVALID = "OUTPUT_DOMAIN_INVALID"
    OUTPUT_CLASS_ID_INVALID = "OUTPUT_CLASS_ID_INVALID"
    OUTPUT_BOX_INVALID = "OUTPUT_BOX_INVALID"
    OUTPUT_CONTRACT_UNAVAILABLE = "OUTPUT_CONTRACT_UNAVAILABLE"
    OUTPUT_CONTRACT_UNVERIFIABLE = "OUTPUT_CONTRACT_UNVERIFIABLE"
    OUTPUT_HASH_MISMATCH = "OUTPUT_HASH_MISMATCH"
    OUTPUT_RESOURCE_LIMIT_EXCEEDED = "OUTPUT_RESOURCE_LIMIT_EXCEEDED"
    OUTPUT_PROBABILITY_SUM_INVALID = "OUTPUT_PROBABILITY_SUM_INVALID"
    OUTPUT_MUTATION_DETECTED = "OUTPUT_MUTATION_DETECTED"

    # Input-Output Binding Findings (Phase 10.7)
    INFERENCE_BINDING_INPUT_MISSING = "INFERENCE_BINDING_INPUT_MISSING"
    INFERENCE_BINDING_MODEL_MISSING = "INFERENCE_BINDING_MODEL_MISSING"
    INFERENCE_BINDING_PREPROCESSING_MISSING = "INFERENCE_BINDING_PREPROCESSING_MISSING"
    INFERENCE_BINDING_EXECUTION_MISSING = "INFERENCE_BINDING_EXECUTION_MISSING"
    INFERENCE_BINDING_OUTPUT_MISSING = "INFERENCE_BINDING_OUTPUT_MISSING"
    INFERENCE_BINDING_PROJECT_MISMATCH = "INFERENCE_BINDING_PROJECT_MISMATCH"
    INFERENCE_BINDING_COMPONENT_MISMATCH = "INFERENCE_BINDING_COMPONENT_MISMATCH"
    INFERENCE_BINDING_HASH_MISMATCH = "INFERENCE_BINDING_HASH_MISMATCH"
    INFERENCE_BINDING_RAW_OUTPUT_MISMATCH = "INFERENCE_BINDING_RAW_OUTPUT_MISMATCH"
    INFERENCE_BINDING_VALIDATED_OUTPUT_MISMATCH = "INFERENCE_BINDING_VALIDATED_OUTPUT_MISMATCH"
    INFERENCE_BINDING_UNAVAILABLE = "INFERENCE_BINDING_UNAVAILABLE"
    INFERENCE_BINDING_UNVERIFIABLE = "INFERENCE_BINDING_UNVERIFIABLE"

    # Inference Record Findings (Phase 10.8)
    INFERENCE_RECORD_INVALID = "INFERENCE_RECORD_INVALID"
    INFERENCE_RECORD_TAMPERED = "INFERENCE_RECORD_TAMPERED"
    INFERENCE_RECORD_PROJECT_MISMATCH = "INFERENCE_RECORD_PROJECT_MISMATCH"
    INFERENCE_RECORD_BINDING_INVALID = "INFERENCE_RECORD_BINDING_INVALID"
    INFERENCE_RECORD_BINDING_UNAVAILABLE = "INFERENCE_RECORD_BINDING_UNAVAILABLE"
    INFERENCE_RECORD_HASH_MISMATCH = "INFERENCE_RECORD_HASH_MISMATCH"
    INFERENCE_RECORD_VERSION_UNSUPPORTED = "INFERENCE_RECORD_VERSION_UNSUPPORTED"
    INFERENCE_RECORD_IMMUTABLE_FIELD_MODIFIED = "INFERENCE_RECORD_IMMUTABLE_FIELD_MODIFIED"
    INFERENCE_RECORD_PERSISTENCE_FAILURE = "INFERENCE_RECORD_PERSISTENCE_FAILURE"
    INFERENCE_RECORD_NOT_FOUND = "INFERENCE_RECORD_NOT_FOUND"


