"""Enumerations for Cross-Subsystem Evidence Ingestion (Phase 12.4)."""

from enum import Enum


class IngestionSchemaVersion(str, Enum):
    """SemVer for Universal Evidence Ingestion contracts."""
    V1_0 = "1.0.0"


class IngestionStatus(str, Enum):
    """Result status for evidence ingestion."""
    INGESTED = "INGESTED"
    DUPLICATE_SKIPPED = "DUPLICATE_SKIPPED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"


class IngestionErrorType(str, Enum):
    """Typed error classifications for ingestion validation failures."""
    INVALID_SCHEMA = "INVALID_SCHEMA"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    DOMAIN_MISMATCH = "DOMAIN_MISMATCH"
    PROJECT_BOUNDARY_VIOLATION = "PROJECT_BOUNDARY_VIOLATION"
    ASSET_BOUNDARY_VIOLATION = "ASSET_BOUNDARY_VIOLATION"
    SOURCE_HASH_MISMATCH = "SOURCE_HASH_MISMATCH"
    CANONICAL_HASH_MISMATCH = "CANONICAL_HASH_MISMATCH"
    IDENTITY_MISMATCH = "IDENTITY_MISMATCH"
    ANCESTRY_CONFLICT = "ANCESTRY_CONFLICT"
    INVALID_CONFIDENCE = "INVALID_CONFIDENCE"
    INVALID_PROOF_CONFIDENCE = "INVALID_PROOF_CONFIDENCE"
    UNSUPPORTED_EVIDENCE = "UNSUPPORTED_EVIDENCE"
    RESOURCE_LIMIT = "RESOURCE_LIMIT"
    DUPLICATE_CONFLICT = "DUPLICATE_CONFLICT"
    INVALID_PROVENANCE = "INVALID_PROVENANCE"
    INVALID_PAYLOAD = "INVALID_PAYLOAD"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
