"""Enumerations for the AIVARA Attack Simulation Lab (Phase 13)."""

from __future__ import annotations

from enum import Enum


class AttackDomain(str, Enum):
    """Target assurance domains for attack simulation."""
    DATASET_INTEGRITY = "DATASET_INTEGRITY"
    CONTRIBUTOR_RISK = "CONTRIBUTOR_RISK"
    MODEL_INTEGRITY = "MODEL_INTEGRITY"
    BEHAVIORAL_INTEGRITY = "BEHAVIORAL_INTEGRITY"
    BACKDOOR_TRIGGER = "BACKDOOR_TRIGGER"
    INFERENCE_INTEGRITY = "INFERENCE_INTEGRITY"
    DISTRIBUTION_SHIFT = "DISTRIBUTION_SHIFT"
    PROOF_PROVENANCE = "PROOF_PROVENANCE"
    SECURITY_BOUNDARY = "SECURITY_BOUNDARY"
    MULTI_DOMAIN = "MULTI_DOMAIN"


class AttackClass(str, Enum):
    """Discrete attack taxonomy categories."""
    # Dataset Integrity
    SAMPLE_POISONING = "SAMPLE_POISONING"
    LABEL_FLIPPING = "LABEL_FLIPPING"
    DUPLICATE_INJECTION = "DUPLICATE_INJECTION"
    SAMPLE_CORRUPTION = "SAMPLE_CORRUPTION"
    
    # Contributor Risk
    SOURCE_FRAGMENTATION = "SOURCE_FRAGMENTATION"
    BURSTY_CONTRIBUTION = "BURSTY_CONTRIBUTION"
    ANOMALOUS_SOURCE_RATIO = "ANOMALOUS_SOURCE_RATIO"
    
    # Model Integrity
    MODEL_BYTE_MUTATION = "MODEL_BYTE_MUTATION"
    MODEL_SUBSTITUTION = "MODEL_SUBSTITUTION"
    CONTRACT_VIOLATION = "CONTRACT_VIOLATION"
    FINGERPRINT_MISMATCH = "FINGERPRINT_MISMATCH"
    
    # Behavioral Integrity
    OUTPUT_INSTABILITY = "OUTPUT_INSTABILITY"
    PERTURBATION_DRIFT = "PERTURBATION_DRIFT"
    ANOMALY_ESCALATION = "ANOMALY_ESCALATION"
    
    # Backdoor Trigger
    TRIGGER_PATTERN_INJECTION = "TRIGGER_PATTERN_INJECTION"
    TRIGGER_ACTIVATION = "TRIGGER_ACTIVATION"
    
    # Inference Integrity
    INPUT_MUTATION = "INPUT_MUTATION"
    PREPROCESSING_MISMATCH = "PREPROCESSING_MISMATCH"
    OUTPUT_SCHEMA_TAMPERING = "OUTPUT_SCHEMA_TAMPERING"
    REPLAY_DIVERGENCE = "REPLAY_DIVERGENCE"
    BINDING_MISMATCH = "BINDING_MISMATCH"
    
    # Distribution Shift
    FEATURE_SHIFT = "FEATURE_SHIFT"
    CATEGORICAL_DRIFT = "CATEGORICAL_DRIFT"
    IMAGE_DESCRIPTOR_SHIFT = "IMAGE_DESCRIPTOR_SHIFT"
    EMBEDDING_DRIFT = "EMBEDDING_DRIFT"
    TEMPORAL_SHIFT = "TEMPORAL_SHIFT"
    
    # Proof / Provenance
    PROOF_SIGNATURE_TAMPERING = "PROOF_SIGNATURE_TAMPERING"
    PROVENANCE_CHAIN_SEVERANCE = "PROVENANCE_CHAIN_SEVERANCE"
    PROOF_CONFIDENCE_SPOOFING = "PROOF_CONFIDENCE_SPOOFING"
    
    # Security Boundary
    CROSS_PROJECT_BOLA = "CROSS_PROJECT_BOLA"
    PATH_TRAVERSAL_ATTEMPT = "PATH_TRAVERSAL_ATTEMPT"
    OVERSIZED_PAYLOAD_EXHAUSTION = "OVERSIZED_PAYLOAD_EXHAUSTION"
    
    # Multi-Domain Composition
    MULTI_DOMAIN_CORRELATED = "MULTI_DOMAIN_CORRELATED"


class MutationType(str, Enum):
    """Deterministic mutation operators applied to fixtures."""
    BIT_FLIP = "BIT_FLIP"
    VALUE_SUBSTITUTION = "VALUE_SUBSTITUTION"
    NOISE_INJECTION = "NOISE_INJECTION"
    LABEL_SWAP = "LABEL_SWAP"
    RECORD_DUPLICATION = "RECORD_DUPLICATION"
    RECORD_DELETION = "RECORD_DELETION"
    SIGNATURE_CORRUPTION = "SIGNATURE_CORRUPTION"
    METRIC_SCALING = "METRIC_SCALING"
    SCHEMA_TAMPERING = "SCHEMA_TAMPERING"
    TENANT_OVERRIDE = "TENANT_OVERRIDE"


class SimulationStatus(str, Enum):
    """Lifecycle state of an attack simulation execution."""
    INITIALIZED = "INITIALIZED"
    GENERATING_FIXTURES = "GENERATING_FIXTURES"
    EXECUTING_CLEAN = "EXECUTING_CLEAN"
    EXECUTING_ATTACK = "EXECUTING_ATTACK"
    EVALUATING_ORACLE = "EVALUATING_ORACLE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class OracleOutcome(str, Enum):
    """Classification of simulation results against expected oracle criteria."""
    EXPECTED_DETECTION = "EXPECTED_DETECTION"
    EXPECTED_NO_DETECTION = "EXPECTED_NO_DETECTION"
    FALSE_NEGATIVE = "FALSE_NEGATIVE"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    UNEXPECTED_FAILURE = "UNEXPECTED_FAILURE"
    BLOCKED_BY_POLICY = "BLOCKED_BY_POLICY"
    BLOCKED_BY_RESOURCE = "BLOCKED_BY_RESOURCE"
    INVALID_SCENARIO = "INVALID_SCENARIO"


class ExpectedDecisionClass(str, Enum):
    """Expected policy decision category for oracle validation."""
    ACCEPT = "ACCEPT"
    REVIEW = "REVIEW"
    QUARANTINE = "QUARANTINE"
    REJECT = "REJECT"
    ANY_ELEVATED = "ANY_ELEVATED"  # REVIEW, QUARANTINE, or REJECT
